import { jsxs as _jsxs, jsx as _jsx } from "react/jsx-runtime";
import { num } from "../utils/formatting";
function parseApiTimestamp(value) {
    if (!value)
        return null;
    const normalized = /([zZ]|[+-]\d{2}:\d{2})$/.test(value) ? value : `${value}Z`;
    const parsed = new Date(normalized);
    return Number.isNaN(parsed.getTime()) ? null : parsed;
}
export default function SelectedAssetLivePanel({ symbol, assetControl, openPositions }) {
    return (_jsxs("section", { style: { borderBottom: "1px solid #22262f" }, children: [_jsxs("div", { style: { padding: "8px 10px", fontSize: 12, fontWeight: 600 }, children: ["Selected Asset Live Data \u2014 ", symbol] }), _jsx("div", { style: { overflowX: "auto", borderTop: "1px solid #1b1f29" }, children: _jsxs("table", { style: { width: "100%", borderCollapse: "collapse", fontSize: 12 }, children: [_jsx("thead", { children: _jsxs("tr", { children: [_jsx("th", { style: { textAlign: "left", padding: 8 }, children: "Run" }), _jsx("th", { style: { textAlign: "left", padding: 8 }, children: "Mode" }), _jsx("th", { style: { textAlign: "left", padding: 8 }, children: "Side" }), _jsx("th", { style: { textAlign: "right", padding: 8 }, children: "Current Risk" }), _jsx("th", { style: { textAlign: "left", padding: 8 }, children: "Last Run" }), _jsx("th", { style: { textAlign: "left", padding: 8 }, children: "Next Run" }), _jsx("th", { style: { textAlign: "left", padding: 8 }, children: "State" })] }) }), _jsx("tbody", { children: _jsxs("tr", { style: { borderTop: "1px solid #1b1f29" }, children: [_jsx("td", { style: { padding: 8 }, children: assetControl ? (assetControl.enabled ? "Run" : "Paused") : "-" }), _jsx("td", { style: { padding: 8 }, children: assetControl ? (assetControl.execution_mode === "sim" ? "Sim" : "Real") : "-" }), _jsx("td", { style: { padding: 8 }, children: assetControl
                                            ? assetControl.trade_side === "long_short"
                                                ? "Long+Short"
                                                : assetControl.trade_side === "short_only"
                                                    ? "Short"
                                                    : "Long"
                                            : "-" }), _jsx("td", { style: { textAlign: "right", padding: 8 }, children: assetControl ? num(assetControl.current_risk_usd, 4) : "-" }), _jsx("td", { style: { padding: 8 }, children: parseApiTimestamp(assetControl?.last_run_ts)?.toLocaleString() ?? "-" }), _jsx("td", { style: { padding: 8 }, children: parseApiTimestamp(assetControl?.next_run_ts)?.toLocaleString() ?? "-" }), _jsx("td", { style: { padding: 8 }, children: assetControl?.last_evaluated_state ?? "-" })] }) })] }) }), _jsx("div", { style: { overflowX: "auto", borderTop: "1px solid #1b1f29" }, children: _jsxs("table", { style: { width: "100%", borderCollapse: "collapse", fontSize: 12 }, children: [_jsx("thead", { children: _jsxs("tr", { children: [_jsx("th", { style: { textAlign: "left", padding: 8 }, children: "Open Positions (Asset)" }), _jsx("th", { style: { textAlign: "left", padding: 8 }, children: "Side" }), _jsx("th", { style: { textAlign: "right", padding: 8 }, children: "Entry" }), _jsx("th", { style: { textAlign: "right", padding: 8 }, children: "Last" }), _jsx("th", { style: { textAlign: "right", padding: 8 }, children: "Qty" }), _jsx("th", { style: { textAlign: "right", padding: 8 }, children: "Unrealized P&L" })] }) }), _jsx("tbody", { children: openPositions.length === 0 ? (_jsx("tr", { style: { borderTop: "1px solid #1b1f29" }, children: _jsxs("td", { style: { padding: 8 }, colSpan: 6, children: ["No open positions for ", symbol, "."] }) })) : (openPositions.map((row) => (_jsxs("tr", { style: { borderTop: "1px solid #1b1f29" }, children: [_jsx("td", { style: { padding: 8 }, children: row.symbol }), _jsx("td", { style: { padding: 8 }, children: row.trade_side === "short" ? "Short" : "Long" }), _jsx("td", { style: { textAlign: "right", padding: 8 }, children: num(row.entry_price, 6) }), _jsx("td", { style: { textAlign: "right", padding: 8 }, children: num(row.last_price, 6) }), _jsx("td", { style: { textAlign: "right", padding: 8 }, children: num(row.qty, 6) }), _jsx("td", { style: { textAlign: "right", padding: 8 }, children: num(row.unrealized_pnl, 6) })] }, row.id)))) })] }) })] }));
}
